config/routes.rb
Whiteboard::Application.routes.draw do
  resources :tasks do
    collection do
      put 'share'
    end
  end
  resources :accomplishments
  get 'today' => 'accomplishments#today'
  get 'progress' => 'accomplishments#index'

  devise_for :users

  root :to => 'accomplishments#index'

end

app/models/task.rb
class Task
  include Mongoid::Document
  include Mongoid::Timestamps
  has_and_belongs_to_many :users
  has_many :accomplishments
  field :description, type: String
  field :daily_limit, type: Integer, default: 1
  field :points, type: Float
  def max_points
  	return self.points * self.daily_limit
  end
  def possible_scores
    return (0..self.daily_limit).map{|x| x*self.points }
  end
  # validate that points assigned are not below 0 or above max
  def share_with(from_user, other_user)
    if from_user.tasks.include? self
      other_user.tasks.push(self)
      # may be pointless:
      other_user.save
    else
      errors.add(:users, 'You must have access to this task to share it')
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :new]
  load_and_authorize_resource

  # GET /tasks
  # GET /tasks.json
  def index
    if current_user && current_user.admin?
      @tasks = Task.all
    elsif current_user
      @tasks = current_user.tasks
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/share?task_id=:task_id&user_id=:user_id
  def share
    @task = Task.find(params[:task_id])
    @to_user = User.find(params[:user_id])
    @from_user = current_user

    respond_to do |format|
      if @task.share_with(@from_user, @to_user)
        format.html { redirect_to @task, notice: 'Successfully shared task with '+@to_user.email }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :points %>
    <%= f.number_field :points, :step => 0.1 %>
  </div>
  <div class="field">
    <%= f.label :daily_limit %>
    <%= f.number_field :daily_limit %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<!-- show accomplishments if any in a table -->

<% if @tasks.any? %>
<table class='table table-condensed'>
  <tr>
    <th>Description</th>
    <th>Points</th>
    <th>Daily Limit</th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.description, task %></td>
    <td><%= best_in_place task, :points, :type => :input %></td>
    <td><%= task.daily_limit %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<% else %>
<script type="text/javascript">
  $(document).on('ready', function(){
    $('#new_task').addClass('lead')
  })
</script>
<% end %>

<br />

<%= link_to 'New Task', new_task_path, :id => 'new_task' %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <b>Description:</b>
  <%= @task.description %>
</p>
<p>
  <b>Points:</b>
  <%= @task.points %>
</p>
<p>
  <b>Daily Limit:</b>
  <%= @task.daily_limit %>
</p>

<p>
	<b>Users:</b>
	<ol>
		<% @task.users.each do |u| %>
			<li><%= u.email %></li>
		<% end %>
	</ol>
</p>

<p>
  <b>Share Task:</b>
  <%= form_tag share_tasks_path, :method => 'put' do %>
  	<%= hidden_field_tag :task_id, @task.id %>
  	<!-- select tag from collection -->
  	<%= select_tag "user_id", options_from_collection_for_select(User.all, "id", "email") %><br>
  	<%= submit_tag :share, :class => 'btn btn-primary' %> 
    <%= link_to 'Edit', edit_task_path(@task) %> |
    <%= link_to 'Back', tasks_path %>  
  <% end %>
</p>

<table>
  <caption>Recent Accomplishments</caption>
  <thead>
    <th>Score</th>
    <th>Completed At</th>
  </thead>
  <tbody>
  <% @task.accomplishments.order_by([:created_at, :desc]).limit(10).each do |acc| %>
    <tr>
      <td><%= acc.score %></td>
      <td><%= time_tag acc.completed_at if acc.completed_at %></td>
    </tr>
  <% end %>
  </tbody>
</table>