config/routes.rb
Whiteboard::Application.routes.draw do
  resources :tasks do
    collection do
      put 'share'
    end
  end
  resources :accomplishments
  get 'today' => 'accomplishments#today'
  get 'progress' => 'accomplishments#index'

  devise_for :users

  root :to => 'accomplishments#index'

end

app/views/layouts/_footer.html.erb
<br>
<div class='row-fluid'>
  <div class='centered-text'>
    by <%= link_to "Hayk Saakian | my [t]", "http://twitter.com/hayksaakian", :rel => 'author' %> | 
    <%= link_to 'my [G+]', 'https://plus.google.com/113832802297823397419/', :rel => 'author' %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
<div id="purr-container" class='the_real_container'></div>

app/views/layouts/_navigation.html.erb
<span class='brand'><%= link_to'<strong>Life</strong>board'.html_safe, root_url %></span>
<div class='pull-right'>
  <ul class="nav">
		<% if user_signed_in? %>
		  <li>
		  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
		  </li>
		<% else %>
		  <li>
		  <%= link_to('Login', new_user_session_path)  %>
		  </li>
		<% end %>
		<% if user_signed_in? %>
		  <li>
		  <%= link_to('Edit account', edit_user_registration_path) %>
		  </li>
		<% else %>
		  <li>
		  <%= link_to('Sign up', new_user_registration_path)  %>
		  </li>
		<% end %>
  </ul>
</div>

<div class='pull-left'>
	<ul class='nav'>
		<li><%= link_to 'Progress', progress_path %></li>
		<!-- <li><%= link_to 'Today', today_path %></li>
		 --><li><%= link_to 'Tasks', tasks_path %></li>
		<li><%= link_to 'New Task', new_task_path %></li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lifeboard" %></title>
    <meta name="description" content="day to day progress tracking for life">
    <meta name="author" content="Hayk Saakian">
    <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
    <%#= analytics_init if Rails.env.production? %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-inverse navbar-static-top">
      <nav class="navbar-inner">
        <div class="container-fluid">
      		<%= render 'layouts/navigation' %>          
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <div id='alert_messages'>
          		  <%= render 'layouts/messages' %>
              </div>
              <div><%= yield %></div>
            </div>
          </div>
        </div>
        <footer>         
          <%= render 'layouts/footer' %>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>